---
title: "PSet_explore_one_varible"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

```{r Load diamonds and summarize}
data(diamonds)
```

```{r}
cheap_diamonds <- subset(diamonds, price <= 500)
cheaper_diamonds <- subset(diamonds, price <= 250)
expensive_diamonds <- subset(diamonds, price >= 15000)
```

```{r}
qplot(x=price, data=diamonds)
```

```{r}
ggplot(aes(x=price), data=diamonds,
       binwidth = 10) +
  geom_histogram() + 
  scale_x_continuous(limits=c(300,500), breaks = seq(300,500, 25))
```

```{r}
ggplot(aes(x=price), data=diamonds) + 
  geom_histogram() + 
  facet_wrap(~cut)
```

```{r}
by(diamonds$price, diamonds$cut, summary)
```

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = "free_y")
```

```{r}
ggplot(aes(log10(price)), data = diamonds, binwidth=25) + 
  geom_histogram() + 
  facet_wrap(~cut, scales = "free_y")
```

```{r}
ggplot(aes(color, price), data=diamonds) +
  geom_boxplot()
```

```{r}
IQR(subset(diamonds, color=="D")$price)
IQR(subset(diamonds, color=="J")$price)
by(diamonds$price, diamonds$color, summary)
```

```{r}
qplot(x = color, y = price/carat, data = diamonds, geom='boxplot') +
  coord_cartesian(ylim=c(0,6000))
```


```{r}
ggplot(aes(color, price/carat), data = diamonds) + 
  geom_boxplot()
```

```{r}
ggplot(aes(carat), data=diamonds, binwidth=0.1) + 
  geom_freqpoly() + 
  scale_x_continuous(breaks = seq(0,5,0.1)) + 
  scale_y_continuous(limits = c(0,2100))

table(diamonds$carat)
```

