```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
data(diamonds)
```

```{r}
ggplot(aes(price, x), data = diamonds) + 
  geom_point()
```

```{r}
cor.test(diamonds$price, diamonds$x)
cor.test(diamonds$price, diamonds$y)
cor.test(diamonds$price, diamonds$z)
```

```{r}
ggplot(aes(depth, price), data = diamonds) + 
  geom_point(alpha = 1/100) + 
  scale_x_continuous(breaks = seq(0, 79, 2))
```

```{r}
cor.test(diamonds$depth, diamonds$price)
```

```{r}
ggplot(aes(carat, price), 
       data = subset(diamonds, diamonds$price < quantile(diamonds$price, probs = 0.99) &
                       diamonds$carat < quantile(diamonds$carat, probs = 0.99))) + 
  geom_point()
```

```{r}
ggplot(aes(x = carat, y = price), 
       data = subset(diamonds, diamonds$price < quantile(diamonds$price, 0.99) &
                       diamonds$carat < quantile(diamonds$carat, 0.99))) + 
  geom_point()
```

```{r}
ggplot(aes((x*y*z), price), data = diamonds) + 
  geom_point()
```

```{r}
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z
#count(diamonds$volume)
```

```{r}
cor.test(subset(diamonds$price, !diamonds$volume== 0 & !diamonds$volume >= 800), subset(diamonds$volume, !diamonds$volume== 0 & !diamonds$volume >= 800))
```

```{r}
ggplot(aes((x*y*z), price), 
       data = subset(diamonds, !diamonds$volume== 0 & !diamonds$volume >= 800)) + 
  geom_point(alpha = 1/25) + 
  geom_smooth(span = 5)
```

```{r}
diamondsByClarity <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_price = mean(price),
            median_price = median(price), 
            min_price = min(price),
            max_price = max(price),
            n = n()) 
```

```{r}
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))
diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))
```

```{r}
b1 <- ggplot(aes(x= clarity, y = mean_price), data = diamonds_mp_by_clarity) + geom_bar(stat="identity")
b2 <- ggplot(aes(color, mean_price), data = diamonds_mp_by_color) + geom_bar(stat="identity")
```

```{r}
grid.arrange(b1, b2, ncol=1)
```

